behaviors:
    DReCon-Mj:
        trainer_type: ppo
        hyperparameters:
            num_epoch: 3
            beta: 0.002
            epsilon: 0.2
            learning_rate: 5e-5
            batch_size: 2048 
            buffer_size: 40960 # 768 * 4
        summary_freq: 50000
        checkpoint_interval: 500000
        keep_checkpoints: 5
        reward_signals:
            extrinsic:
                gamma: 0.995
                strength: 1.0
                network_settings:
                    normalize: true
                    num_layers: 3
                    hidden_units: 512  
        network_settings:
            num_layers: 3
            hidden_units: 512    
            normalize: true
        max_steps: 30000000
        time_horizon: 1024
   
   
