name: Upstream Sync

on:
  schedule:
  - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  sync-with-upstream:
    runs-on: ubuntu-latest
    environment: OpenUPM workflows
    name: Sync main with upstream latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0
    - name: Sync master with upstream latest
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
      with:
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_repo: Balint-H/modular-agents
        upstream_sync_branch: main
        target_sync_branch: main
        upstream_pull_args: --tags
        target_branch_push_args: --tags
    - name: Show value of 'has_new_commits'
      run: |
        echo ${{ steps.sync.outputs.has_new_commits }}
    - name: Create runs for new tags
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_FULL_NAME: ${{ github.repository }}
      run: |
        gh repo set-default $REPO_FULL_NAME
        UPM_TAGS="$(git tag --merged origin/upm)"
        MAIN_TAGS="$(git tag --merged origin/main)"
        NEW_TAGS=$(grep -Fxvf <($UPM_TAGS) <(echo "$MAIN_TAGS"))
        echo "New tags detected: $NEW_TAGS"

        echo "$NEW_TAGS" | while read TAG
        do
          echo "===== $TAG"
          echo "Creating workflow"
          gh workflow run to-upm.yml -f tag_name=$TAG
          echo "Workflow created, waiting..."
          RUN_ID=$(gh run list --json databaseId --workflow to-upm.yml --limit 1 | jq -r '.[0].databaseId') # https://stackoverflow.com/a/77825187/6702274
          gh run watch RUN_ID --exit-status
          echo "Workflow finished"
          echo "====="
        done
