name: Upstream Sync

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  sync-with-upstream:
    runs-on: ubuntu-latest
    environment: OpenUPM workflows
    name: Sync main with upstream latest
    
    steps:
    - name: Checkout master
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
        ref: main
    - name: Sync master with upstream latest
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
      with:
        target_repo_token: ${{ secrets.ACCESS_TOKEN }}
        upstream_sync_repo: Balint-H/modular-agents
        upstream_sync_branch: main
        target_sync_branch: main
        upstream_pull_args: --tags
        target_branch_push_args: --tags
        test_mode: true
    - name: Show value of 'has_new_commits'
      run: echo ${{ steps.sync.outputs.has_new_commits }}