name: UPM Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag to merge"
        required: true
        type: string
  push:
    tags:
    - '*'
    - '!upm-*'

jobs:
  sync-to-upm:
    runs-on: ubuntu-latest
    steps:
    - name: Set environment variables
      run: |
        echo "TAG_NAME=${{ inputs.tag_name || env.GITHUB_REF_NAME }}" >> $GITHUB_ENV
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: upm
    - name: Setup user
      uses: fregante/setup-git-user@v2
    - name: Merge 1
      continue-on-error: true
      run: |
        git merge --no-commit --no-ff ${{ env.TAG_NAME }}
    - name: Merge 2
      run: |
        git reset -- .github
        git commit --no-edit
        git push
        echo "MERGE_COMMIT_HASH=$(git rev-parse --verify HEAD)" >> $GITHUB_ENV
    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: upm-${{ env.TAG_NAME }}
        release_name: UPM - ${{ env.TAG_NAME }}
        commitish: ${{ env.MERGE_COMMIT_HASH }}
